### ISSUE TITLE
Add ReccuringEvents to database, and retrieve them from DB

### ISSUE THREAD

**Issue by AlonSchwartz** [elchi28/Hostel-Harmony#62]
### Tasks
- [x] add to DB
- [x] get from DB
- [ ] delete from DB (optional)
